### PR TITLE
feat: add support for Windows Server 2025 Insiders Preview

### PR DESCRIPTION
**Pull request by rcroft-work**
# 

## Summary of Pull Request

This PR adds support for Windows Server 2025 Insiders Previews to enable customers to try/test these releases.

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [X] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Resolves: #833 
Issue Number: #833

## Test and Documentation Coverage

- [ ] Tests have been completed.
- [X] Documentation has been added or updated.

Updated the changelog.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
LGTM - needs an update to the README.md and the /docs for the OS listings

**Comment by tenthirtyam** [comment]
And this file too, please. 🙃

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/docs/index.md

**Comment by rcroft-work** [comment]
Done, `docs/index.md` updated.

**Comment by rcroft-work** [comment]
Okay, now `docs/index.md` really has been updated.

**Review by tenthirtyam — APPROVED** [review]
LHTM!

**Pull request merged**
