### PR TITLE
fix: debian 12 mount of  `/dev/sr1` with  `http` data source

### LINKED ISSUE #673: `develop`: Debian mount of  `/dev/sr1` with  `http` data source
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3d

### HashiCorp Packer

1.9.1

### HashiCorp Packer Plugin for VMware vSphere

1.2.0

### Guest Operating System

Ubuntu 22.04

### Environment Details

_No response_

### Description

Hello,

In config/common.pkrvars.hcl, I've setup : 

```
// Boot and Provisioning Settings
common_data_source      = "http"
common_http_ip          = "192.168.0.42"
```

so I was surprised to see linux-debian.pkr.hcl [containing](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/7c95458386a29e8ab458e6ea0d2be3a9f75f4536/builds/linux/debian/12/linux-debian.pkr.hcl#L127) 

`mount /dev/sr1 /media<enter>`

in its boot_command.

In the first place, `/dev/sr1` is not found, and this command is failing. Luckily, it has no ill effects as I'm using the internal http server.

At the [end of the kickstart](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/7c95458386a29e8ab458e6ea0d2be3a9f75f4536/builds/linux/debian/12/data/ks.pkrtpl.hcl#L181), the `common_data_source` value is tested and the cdrom would then be unmounted.
As common_data_source equals http, this unmount is not tried, so far so good.

As I was worried some pieces of software could have been missing from the failing mount of `/dev/sr1`, I changed it to `/dev/sr0` which device is found then mounted. (I changed it at the mount and unmount places)
This was a bad idea because now the mount is working, the unmount is not even tried because `common_data_source` equals `http`.
And after the VM reboot, this leads to a VM booting again onto the still present cdrom instead of the disk, and staying still at the debian install prompt.

Anyway, this all is no big deal (in the `http` case), but it looks like some clarification is needed (What was the point trying to mount the cdrom after a 30 seconds wait?), or at least some way to align the boot_command and the kickstart in respect to the `common_data_source` value.

### Expected Behavior

In the http case, not even try to mount the cdrom.

### Actual Behavior

The cdrom mount after the 30s wait is failing, and seems pointless.

### Steps to Reproduce

Use the develop branch for debian 12

### Log Fragments and Files

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by necarnot**
# 

## Summary of Pull Request

Fix Debian 12 mount of  `/dev/sr1` with  `http` data source.

## Type of Pull Request

- [x] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Closes #673

## Test and Documentation Coverage

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Please duplicate for Debian 11.

**Comment by tenthirtyam** [comment]
@necarnot I've corrected the pull request title and have placed the template body. Could you fill this out for completeness?

**Comment by tenthirtyam** [comment]
Marking as draft until the CLA is approved.

**Comment by necarnot** [comment]
> Please duplicate for Debian 11.

https://github.com/vmware-samples/packer-examples-for-vsphere/pull/686

**Review by tenthirtyam — DISMISSED** [review]
LGTM! 🚀

**Pull request merged**
