### PR TITLE
fix: windows 11 guest customization failure

### PR DESCRIPTION
**Pull request by LukeEvansTech**
# 

## Summary of Pull Request

At present, when using a Packer built Windows 11 image, the guest customization step fails when deploying with Terraform.

Sysprep is failing with the following:

```console
2023-01-06 23:35:44, Error                 SYSPRP Package BytedancePte.Ltd.TikTok_1.0.5.0_neutral__6yccndn6064se was installed for a user, but not provisioned for all users. This package will not function properly in the sysprep image.
2023-01-06 23:35:44, Error                 SYSPRP Failed to remove apps for the current user: 0x80073cf2.
2023-01-06 23:35:44, Error                 SYSPRP Exit code of RemoveAllApps thread was 0x3cf2.
2023-01-06 23:35:44, Error                 SYSPRP ActionPlatform::LaunchModule: Failure occurred while executing 'SysprepGeneralizeValidate' from C:\Windows\System32\AppxSysprep.dll; dwRet = 0x3cf2
2023-01-06 23:35:44, Error                 SYSPRP SysprepSession::Validate: Error in validating actions from C:\Windows\System32\Sysprep\ActionFiles\Generalize.xml; dwRet = 0x3cf2
2023-01-06 23:35:44, Error                 SYSPRP RunPlatformActions:Failed while validating Sysprep session actions; dwRet = 0x3cf2
2023-01-06 23:35:44, Error      [0x0f0070] SYSPRP RunDlls:An error occurred while running registry sysprep DLLs, halting sysprep execution. dwRet = 0x3cf2
2023-01-06 23:35:44, Error      [0x0f00d8] SYSPRP WinMain:Hit failure while pre-validate sysprep generalize internal providers; hr = 0x80073cf2
```

Troubleshooting me led this to KB from VMware
https://kb.vmware.com/s/article/82532

To overcome this, I had to remove the AppX Package 'BytedancePte.Ltd.TikTok_1.0.5.0_neutral__6yccndn6064se' as part of the Packer build

This pull request looks to remove the AppXPackage 'BytedancePte.Ltd.TikTok_1.0.5.0_neutral__6yccndn6064se' as part of the Packer build

## Type of Pull Request

- [x] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [ ] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Comment by LukeEvansTech** [comment]
I would love to know if anyone else is seeing this behavior when deploying Windows 11 builds with Terraform.

**Comment by tenthirtyam** [comment]
Hi @LukeEvansTech,

Per the [CONTRIBUTING](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CONTRIBUTING.md) guidelines, please open an issue for an enhancement and link this pull request to the issue using "Closes #xxx" in the **Related to Existing Issues** section.

Ryan

**Comment by tenthirtyam** [comment]
Marking as draft whilst these updates are made: https://github.com/vmware-samples/packer-examples-for-vsphere/pull/467#issuecomment-1400667909

**Comment by LukeEvansTech** [comment]
Closing this PR and reopening under #467 to swap the branch

**Pull request closed without merging**
