### PR TITLE
feat: Prepare Ubuntu 22.04

### LINKED ISSUE #186: [ENHANCEMENT] Add Ubuntu 22.04 LTS
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

New Ubuntu LTS will be released soon.

### Use Case(s)

Use Ubuntu LTS 22.04.

### Potential Configuration

Add `builds/linux/ubuntu/22.04` build folder.

### References

_No response_

### PR DESCRIPTION
**Pull request by sestegra**
## Type of Pull Request

- [ ] This is a bugfix.
- [X] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

## Context of the Pull Request

Ubuntu 22.04 will be published soon.
To anticipate, I prepare its build.

## Related to Existing Issues

Closes #186 

## Test and Documentation Coverage

- [x] Tests have been completed (for bugfixes / features).
- [ ] Documentation has been added / updated (for bugfixes / features).

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Comment by sestegra** [comment]
Let's wait for next week's beta before merging.
See [Jammy Jellyfish Release Schedule](https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906)

**Comment by tenthirtyam** [comment]
- Holding for testing with Ubuntu 22.04 LTS beta release on March 31st (planned). 
- Onboard with v22.04 project release after the Ubuntu 22.04 LTS release on April 21st GA (planned).

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by sestegra** [comment]
Ready to merge

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Hi, @sestegra 👋,

Could I ask you to update the README.md with the information for Ubuntu 22.04, in the list of distributions in the **Introduction** and **Configuration** Step 2?

Ryan

**Comment by sestegra** [comment]
@tenthirtyam Update done

**Comment by tenthirtyam** [comment]
Many thanks, @sestegra!

**Review by tenthirtyam — APPROVED** [review]
Looks great @sestegra! 🚀 

I sincerely appreciate your contributions to this project!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Pull request merged**
