### PR TITLE
feat: add templated `.gitlab-ci.yml` method

### LINKED ISSUE #674: Add Packer GitLab CI/CD pipelines
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add templated way of generating a `gitlab-ci.yml` file to enable a GitLab CI/CD pipeline to build the Packer templates.

### Use Case(s)

Administrator(s) would like to automate the creation of Packer templates in vSphere via a GitLab CI/CD pipeline.

Administrator(s) would like to automate the creation of GitLab CI/CD pipelines to build Packer templates in vSphere.

### Potential Configuration

Modified or additional gomplate template to create `.gitlab-ci.yml`.

### References

See [Packer Gitlab CI/CD pipelines #654](https://github.com/vmware-samples/packer-examples-for-vsphere/discussions/654) discussion.

### PR DESCRIPTION
**Pull request by rcroft-work**
## Summary of Pull Request

Add templated way of generating a `.gitlab-ci.yml` file to enable a GitLab CI/CD pipeline to build the Packer templates

This change:

- Adds new `build-ci.tmpl` that can be used to crete/update `.gitlab-ci.yml` file
- Adds example `.gitlab.yml` file.
- Adds section to `README.md` describing how to use `build-ci.tmpl` that can be used to create/update `.gitlab-ci.yml` file.

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [X] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Closes #674 

## Test and Documentation Coverage

- [X] Tests have been completed in private GitLab instance
- [X] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]
LGTM! 🚀

**Comment by tenthirtyam** [comment]
@rcroft-work Can you amend and sign the commit https://github.com/vmware-samples/packer-examples-for-vsphere/pull/675/commits/bb913bf0a62e365e3bba405e8c60fb4d33a5e7f2? It's required by the project.

This should do the trick:

```bash
git commit --amend -s bb913bf0a62e365e3bba405e8c60fb4d33a5e7f2
git push --force
```

**Comment by tenthirtyam** [comment]
Marking as draft until commit https://github.com/vmware-samples/packer-examples-for-vsphere/commit/bb913bf0a62e365e3bba405e8c60fb4d33a5e7f2 is signed off.

**Comment by rcroft-work** [comment]
Okay, rebased, signed the commit, and marked as ready for review.

**Review by tenthirtyam — DISMISSED** [review]
LGTM! 🚀

**Pull request merged**
