### PR TITLE
feat: add additional configuration options

### LINKED ISSUE #772: Add additional packer configuration options
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add support for setting additional packer configuration options (resource_pool, set_host_for_datastore_uploads and ip_settle_timeout).

I came across issues on one of our vSphere environments and had to set additional parameters. I have seen various discussions where other users mentioned setting the same parameters on certain configurations so I think it would be useful to include these as options in this project that users can set if they would like.

### Use Case(s)

- On certain environments, packer could not automatically determine the resource pool while creating the VM. By specifying the resource pool in the packer configuration, this allows it to work.
- In some environments I get a 404 when trying to upload the CD content while using "common_data_source" set to "disk". By setting "set_host_for_datastore_uploads" to true, this works around the issue.
- There is an issue in our environment where the IP address changes on the initial reboot. Packer gets stuck trying to connect to the old IP and never finishes. By setting "ip_settle_timeout" to something higher, packer waits that long so gets the correct IP.

### Potential Configuration

Add three new parameters which will be optional.

- vsphere_resource_pool: Resource pool to use, by default will be blank.
- vsphere_set_host_for_datastore_uploads: Whether to set this flag, by default will be false as per packer defaults.
- common_ip_settle_timeout: Time to wait for IP to settle, by default will be 5s as per packer defaults.

### References

Example of upload failure: https://discuss.hashicorp.com/t/vsphere-iso-build-fails-with-404-uploading-iso/49172/7 
Example of IP changing during reboot: https://github.com/hashicorp/packer/issues/11144

### PR DESCRIPTION
**Pull request by DavidRobson**
# 

## Summary of Pull Request

Adds support for setting additional packer configuration options (resource_pool, set_host_for_datastore_uploads and ip_settle_timeout).

I came across issues on one of our vSphere environments and had to set additional parameters. I have seen various discussions where other users mentioned setting the same parameters on certain configurations so I think it would be useful to include these as options in this project that users can set if they would like.

I set default values for these so any existing deployments people have should not break as it should use the defaults and behave as before.

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [x] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Closes #772

## Test and Documentation Coverage

- [x] Tests have been completed.
- [x] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Hi @DavidRobson! 👋 

Thank you for the contribution!

Please sign the VMware CLA and an enhancement issue per the [contributing guidelines](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/CONTRIBUTING.md). Then link the pull request to the issue.

Thank you! 

Ryan

**Comment by tenthirtyam** [comment]
Marked as draft until CLA is signed and enhancement issue is created.

**Comment by DavidRobson** [comment]
@tenthirtyam raised a new issue and linked it, and signed the CLA. I guess we just need to wait for the CLA to be reviewed now.

**Comment by tenthirtyam** [comment]
Thank you! Will merge once the CLA is approved by our OS team.

**Comment by tenthirtyam** [comment]
I'll get this merged today.

**Review by tenthirtyam — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
