### PR TITLE
fix: update windows 2025 defaults

### LINKED ISSUE #906: Windows Server 2025 wrong variables
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.26.7

### Guest Operating System

Windows Server 2025

### Environment Details

_No response_

### Description

In file **windows-server-2025.pkvars.hcl** wrong variables use for keys

Use :
* **vm_inst_kms_key_standard**
* **vm_inst_kms_key_datacenter**

but need to use 
* **vm_inst_os_key_standard**
* **vm_inst_os_key_datacenter**

### Expected Behavior

impossible to startup the build

### Actual Behavior

built must started

### Steps to Reproduce

Launch a build

### Log Fragments and Files

_No response_

### Screenshots

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JM2K69**
# 

## Summary of Pull Request
Updates `builds/windows/server/2025/windows-server.pkrvars.hcl.example` default values to allow for deployment.

- `vm_inst_os_eval = true` >> `vm_inst_os_eval = false` (Insider's Preview)
- `vm_inst_os_kms_key_standard` >> `vm_inst_os_key_standard`
- `vm_inst_os_kms_key_datacenter` >> `vm_inst_os_key_datacenter`

## Type of Pull Request

- [x] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number:  #906

## Test and Documentation Coverage

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Please update the commit message and content using conventional commits as outlined in the CONTRIBUTING.md. Thanks!

**Review by tenthirtyam — COMMENTED** [review]
I've made the necessary changes to follow our guidelines.

**Comment by JM2K69** [comment]
Ok sorry I will do better next times.

**Review by tenthirtyam — APPROVED** [review]
I've modified the pull request to use conventional commits and address the need for eval to be set to `false` for the Insider's Preview.

Also updated the CHANGELOG.md to include this in the v0.20.0 release.

**Comment by tenthirtyam** [comment]
Eek! I just noticed that this was from main >> main instead of develop >> develop.

**Comment by tenthirtyam** [comment]
Fixed!

**Pull request merged**
