### PR TITLE
chore: Update Windows 10/11, Windows Server 2022, and Debian 12 ISOs

### PR DESCRIPTION
**Pull request by rcroft-work**
chore: Update Windows 10/11, Windows Server 2022, and Debian 12 ISOs to latest

# 

## Summary of Pull Request

Updates `.pkrvars.hcl.example` files to latest ISOs for:
- Windows 10
- Windows 11
- Windows Server 2022
- Debian 12

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [X] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [ ] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Mind updating the CHANGELOG.md and I'll merge it in.

**Comment by tenthirtyam** [comment]
Separate line items, please. :)

**Comment by rcroft-work** [comment]
Okay, just going to grab some lunch and will update the changelog when back (w/ separate lines per item 🙂 )

**Comment by rcroft-work** [comment]
Okay, updated the CHANGELOG.md.

**Review by tenthirtyam — APPROVED** [review]
LGTM!!

Thank you!

**Pull request merged**
