### PR TITLE
refactor: use dedicated ansible modules

### PR DESCRIPTION
**Pull request by dhoppe**
## Summary of Pull Request

The existing Ansible playbooks /  roles should use dedicated modules instead of shell commands. 

For example the Ansible module `ansible.posix.authorized_key` automatically creates the `.ssh` directory and handles the permissions of the `authorized_keys` properly. 

I also think that this project will benefit from the error messages that an Ansible module provides. 

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [ ] This is a documentation update. `type/docs`
- [x] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Issue Number: N/A

## Test and Documentation Coverage

- [x] Tests have been completed.
- [ ] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Hi @dhoppe - just check in to see if this is still a work in progress and if it should remain as a draft or ready for review.

Thanks!
Ryan

**Comment by dhoppe** [comment]
@tenthirtyam I am still working on that. Yesterday I did some changes related to `/clean` and I need to cover VMware Photon as well.

**Comment by tenthirtyam** [comment]
Hi @dhoppe - let me know if you might have time to finish this pull request in the next couple of week - hoping to get a release out for end of January `23.

**Comment by dhoppe** [comment]
@tenthirtyam I am really sorry about this, but I am pretty busy right now. Feel free to solve the merge conflict and merge the pull request as it is. Everything else can be switched to Ansible later.

**Comment by tenthirtyam** [comment]
I've rebased this pull request and will be looking into onboarding these great changes soon - _thank you for your patience and contribution!_

**Comment by tenthirtyam** [comment]
Rebased and updated with the newer distributions that have been updated.

This is next in the queue at long last.

cc @rcroft-work

**Review by tenthirtyam — APPROVED** [review]
I've rebased and completed the changes.

**Pull request merged**
