### PR TITLE
fix: gh-197

### LINKED ISSUE #197: [BUG] Setting the `build_password` using `set-envvars.sh`
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

`main`

### VMware vSphere

7.0 Update 2

### HashiCorp Packer

v1.8.0

### HashiCorp Packer Plugin for VMware vSphere

v1.0.3

### Guest Operating System

Any Supported

### Environment Details

The current packer templates seem to not use the `build_password `variable so that the only password read by packer is the one that the user provides in the install script 

I've noticed this situation while working on creating a Debian template starting from the existing template for Ubuntu 18.04.

In order to fix this issue and use the `build_password` variable provided within the `set-envvars.sh` script the following instruction should be added to the templates:

```hcl
build_password = var.build_password
```

### Description

-

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

Run a build setting a password `buid_password` in the config file as "password"
Run the `set-envvars.sh` script and set the password to "different_password"
Run the build.

Result: the password used by packer will be "password" and not "different_password" as expected.

### Log Fragments and Files

_No response_

### Screenshots

_No response_

### Additional Context

-

### PR DESCRIPTION
**Pull request by evilaliv3**
In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CONTRIBUTING.md) for making a pull request.

## Summary of Pull Request

Fix issue GH-197 as discussed in the issue.

## Type of Pull Request

- [X] This is a bugfix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Closes #197

## Test and Documentation Coverage

- [X] Tests have been completed (for bugfixes / features).
- [ ] Documentation has been added / updated (for bugfixes / features).

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Hi @evilaliv3! 👋 

Can you complete the pull request template, please?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
This branch needs to be rebased to upstream `main` so that Ubuntu 22.04 changes are also made.

**Comment by evilaliv3** [comment]
rebased!

**Review by tenthirtyam — APPROVED** [review]
LGTM. 🚀

**Comment by tenthirtyam** [comment]
Awaiting completion of the pull request template and the run of the GHA before merging.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
I've updated the pull request with the completed template.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Pull request merged**
