### PR TITLE
feat: Add a configurable build script

### LINKED ISSUE #187: [ENHANCEMENT] Add a configurable build script
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

The current build script is difficult to maintain when adding or sorting builds.

### Use Case(s)

The build script is configurable with a configuration file.

### Potential Configuration

- Build configuration file to generate build script

### References

_No response_

### PR DESCRIPTION
**Pull request by sestegra**
## Summary of Pull Request

Added a configuration file and a script template to generate a build script.

## Type of Pull Request

- [ ] This is a bugfix.
- [X] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

## Context of the Pull Request

[gomplate](https://gomplate.ca/) is required to generate the build script.
The build script is generated using the following command:
```
gomplate -c build.yaml -f build.tmpl -o build.sh
```

## Related to Existing Issues

Closes #187 

## Test and Documentation Coverage

- [X] Tests have been completed (for bugfixes / features).
- [ ] Documentation has been added / updated (for bugfixes / features).

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
@sestegra, would you mind also updating the README.md for the `gomplate` requirements and present the example use in the steps?

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
LInter error:

```
2022-03-25 19:47:40 [INFO]   File:[/github/workspace/build.tmpl]
[68](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:68)
2022-03-25 19:47:40 [ERROR]   Found errors in [shellcheck] linter!
[69](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:69)
2022-03-25 19:47:40 [ERROR]   Error code: 1. Command output:
[70](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:70)
------
[71](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:71)

[72](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:72)
In /github/workspace/build.tmpl line 22:
[73](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:73)
{{- $func_index := 0 }}
[74](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:74)
 ^-- SC1054 (error): You need a space after the '{'.
[75](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:75)
  ^-- SC1054 (error): You need a space after the '{'.
[76](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:76)
                     ^-- SC1083 (warning): This } is literal. Check expression (missing ;/
[77](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:77)
?) or quote it.
[78](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:78)
                      ^-- SC1083 (warning): This } is literal. Check expression (missing ;/
[79](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:79)
?) or quote it.
[80](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:80)

[81](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:81)

[82](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:82)
In /github/workspace/build.tmpl line 23:
[83](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:83)
{{ range $menu := (ds "build").menu -}}
[84](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:84)
^-- SC1009 (info): The mentioned syntax error was in this brace group.
[85](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:85)
 ^-- SC1054 (error): You need a space after the '{'.
[86](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:86)
 ^-- SC1073 (error): Couldn't parse this brace group. Fix to allow more checks.
[87](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:87)
                  ^-- SC1036 (error): '(' is invalid here. Did you forget to escape it?
[88](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:88)
                  ^-- SC1056 (error): Expected a '}'. If you have one, try a ; or 
[89](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:89)
 in front of it.
[90](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:90)
                  ^-- SC1072 (error): Missing '}'. Fix any mentioned problems and try again.
[91](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:91)

[92](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:92)
For more information:
[93](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:93)
  https://www.shellcheck.net/wiki/SC1054 -- You need a space after the '{'.
[94](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:94)
  https://www.shellcheck.net/wiki/SC1056 -- Expected a '}'. If you have one, ...
[95](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:95)
  https://www.shellcheck.net/wiki/SC1083 -- This } is literal. Check expressi...
[96](https://github.com/vmware-samples/packer-examples-for-vsphere/runs/5697426519?check_suite_focus=true#step:4:96)
------
```

**Comment by sestegra** [comment]
`build.tmpl` is a Golang template, so the linter errors are irrelevant.
I excluded it from the linter.

**Comment by tenthirtyam** [comment]
Thanks, @sestegra! I'll review and test on Monday. Also, thanks for catching the prior spelling errors!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Review by tenthirtyam — APPROVED** [review]
Tested, LGTM! 🚀

**Pull request merged**
