### PR TITLE
fix: repeated line

### LINKED ISSUE #937: There is a line of comment repeated in 'builds/linux/ubuntu-20-04-lts/data/user-data.pkrtpl.hcl'
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### Motivation

There is a typo in

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/d2fde04a56867801bdaeb550e8aed3bf8e62af3f/builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl#L4

as it is probably copy pasted from 

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/d2fde04a56867801bdaeb550e8aed3bf8e62af3f/builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl#L3

by accident. it just bothered me for no reason :)

### Suggestion

Just remove line 4

### PR DESCRIPTION
**Pull request by sepsh**
# 

## Type of Pull Request

- [ ] This is a bugfix. `type/bug`
- [ ] This is an enhancement or feature. `type/feature` or `type/enhancement`
- [x] This is a documentation update. `type/docs`
- [ ] This is a refactoring update. `type/refactor`
- [ ] This is a chore. `type/chore`
- [ ] This is something else.
      Please describe:

## Related to Existing Issues

Closes #937

## Test and Documentation Coverage

- [ ] Tests have been completed.
- [x] Documentation has been added or updated.

## Breaking Changes?

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Hi there @sepsh - thanks for finding this item! Would you mind submitting the required CLA?

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom

**Comment by tenthirtyam** [comment]
Marked as draft until the CLA is signed and submitted.

**Comment by sepsh** [comment]
> Hi there @sepsh - thanks for finding this item! Would you mind submitting the required CLA?
> 
> **Ryan Johnson** Distinguished Engineer, VMware by Broadcom

Hello there, sure anytime.

**Comment by tenthirtyam** [comment]
Pulled into ca58cf14169151ae8bcdfc8c0b6c52f4119bcc05.

**Pull request closed without merging**
